name = "pricel"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
 
[[durable_objects.bindings]]
name = "CANVAS"
class_name = "CanvasEconomy"
 
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CanvasEconomy"]
 
[[d1_databases]]
binding = "DB"
database_name = "pixel-canvas-db"
database_id = "75d56a11-98a4-4c56-ba10-f14bc2f2d3b6"
 
[triggers]
crons = ["0 0 1 * *"]
 
[vars]
ENVIRONMENT = "production"
FREE_CREDITS = "100"
CANVAS_SIZE = "1000"
MAX_SIGNUPS_PER_IP_PER_DAY = "3"
 
